# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-8bmqtBYiYNmgP5JhIiXt3AGo0gZ4OA6
"""

from sklearn.preprocessing import PolynomialFeatures
from sklearn import linear_model
import numpy as np 


#database 
#x = data, y = Target 
x = [[1],[3],[5],[7],[9],[11],[13],[15],[17],[19]]
y = [1, 9, 25, 49, 81, 121, 169, 225, 289, 361] #x dipangkat 2

#data uji 
predict = np.array([[13]]) #nilai yang di prediksi 
poly = PolynomialFeatures(degree=2) #ordo yang digunakan
x_=poly.fit_transform(x) #fitting prediksi sumbu
predict_ = poly.fit_transform(predict) #fitting jenis regresi
regr = linear_model.LinearRegression() #meregresi
regr.fit(x_,y) #menentukan grafik

#menampilkan data prediksi 
print ("Prediksi")
print ("input = ", predict)
print ("Output =", regr.predict(predict_))